[font]
normal = { family = "Hack Nerd Font" }
size = 13.5

# Color Theme - Tokyo Night
#
[colors.normal]
black = "#414868"
blue = "#7dcfff"
cyan = "#2ac3de"
green = "#73daca"
magenta = "#bb9af7"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"