[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font" }
# size = 13.5
size = 14

# Option as Alt
#
[window]
option_as_alt = "Both" # (macos only)
decorations = "None"

# Color Theme - Midnight Haze: <https://github.com/hafiz-muhammad/midnight-haze-alacritty-theme/blob/main/midnight-haze.toml>
#
# Default colors
[colors.primary]
background = "#0c0c16"
foreground = "#d8dee9"

# Normal colors
[colors.normal]
black   = "#2c2c3d"
red     = "#ff6e6e"
green   = "#9ec875"
yellow  = "#ffa759"
blue    = "#70a7d4"
magenta = "#d291e0"
cyan    = "#96e0e0"
white   = "#d8dee9"

# Bright colors
[colors.bright]
black   = "#414166"
red     = "#ff8d8d"
green   = "#b3d987"
yellow  = "#ffc57f"
blue    = "#9bb3d3"
magenta = "#ffa1ff"
cyan    = "#9cd8d8"
white   = "#ffffff"

[keyboard]
bindings = [
  # { key = "Q", mods = "Command", action = "None" }, # This setting is not working. Remapped "Command + Q" to "Hide alacritty" in macOS System Settings instead.
  { key = "W", mods = "Command", action = "None" },
]
